version: '3.1'
services:
  kong-migrations-bootstrap:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kong-island-migrations-bootstrap
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_KEYSPACE=kong_island
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
    external_links:
      - cassandra
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
    command: kong migrations bootstrap
  kong-migrations-up:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kong-island-migrations-up
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_KEYSPACE=kong_island
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
    external_links:
      - cassandra
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
    command: kong migrations up
    depends_on:
      - kong-migrations-bootstrap
  kong:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kong-island-kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_KEYSPACE=kong_island
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
    external_links:
      - cassandra
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
    depends_on:
      - kong-migrations-up
  konga:
    image: pantsel/konga:latest
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=somesecret
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/konga/user.seed
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/konga/node.seed
    volumes:
      - ./konga:/konga:ro
    depends_on:
      - kong
networks:
  default:
    external:
      name: kong-pongo
