version: '3.1'
services:
  konga:
    image: pantsel/konga:latest
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - TOKEN_SECRET=somesecret
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/konga/user.seed
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/konga/node.seed
      - KONGA_LOG_LEVEL=silly
    volumes:
      - ./konga:/konga:ro
    depends_on:
      - kong
