version: '3.1'
services:
  kong:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: kong-island-kong
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_KEYSPACE=kong_island
      - KONG_CASSANDRA_CONTACT_POINTS=cassandra
      - KONG_ADMIN_LISTEN=0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
    depends_on:
      - kong-migrations-up
